# -*- coding: utf-8 -*-
"""Assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/112O6-Dzf1Gkt1dhOes3n-rN4CkERB-eb
"""

import numpy as np
from matplotlib import pyplot as plt

# Declaring the vectors
a = [1,-1,3]
b = [2,-7,1]

#Printing the cross product of a and b for verification
print(np.cross(a, b))
print('Hence,verified.')