# -*- coding: utf-8 -*-
"""Gate_Assignment_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hefPnV6_EVszHSCSiCx9h-HIGbarsPS7
"""

import numpy as np
from matplotlib import pyplot as plt

time = np.linspace(-3,5,10000)
e1 = np.exp(-time/5)

def unit(time):
  x=[]
  for i in time:
    if i<0:
      x.append(0)
    else:
      x.append(1)
  return x  
    
x = 5*(1-e1)*unit(time)
plt.plot(time,x,label='x(t)')
plt.xlabel('t')
plt.ylabel('$x(t)$')
plt.grid()