# -*- coding: utf-8 -*-
"""Quiz_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107v5AL1fxrvRVPZEZ5SPNGkxsM-GTrAA
"""

import numpy as np
from matplotlib import pyplot as plt

def u(x):
    res = []
    for i in range(len(x)):
        if x[i] >=0 :
            res.append(1)
        else:
            res.append(0)
    return res

#Plotting x[n] and h[n]
n = np.arange(-10,10).astype(float)

plt.stem(n , -(2**n)*u(-n-1) ,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$x[n]$')
plt.grid()
plt.show()

plt.stem(n , ((1/3)**n)*u(n),use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$h[n]$')
plt.grid()
plt.show()

n, radii = 50, [1/3 , 2]
pole1 = [1/3,0]
pole2 = [2, 0]
zero = [0,0]

theta = np.linspace(0, 2*np.pi, n, endpoint=True)
xs = np.outer(radii, np.cos(theta))
ys = np.outer(radii, np.sin(theta))

# In order to have a closed area, the circles should be traversed in opposite directions
xs[1,:] = xs[1,::-1]
ys[1,:] = ys[1,::-1]

#Plotting the ROC of Y(z)
ax = plt.subplot(111, aspect='equal')
ax.fill(np.ravel(xs), np.ravel(ys), edgecolor='#348ABD' , label = "$\\frac{1}{3}< |z| < 2$")
plt.plot(np.sin(theta), np.cos(theta) ,'k-',label = "Unit Circle: $|z| = 1$")
plt.plot([pole1[0] , pole2[0]] , [pole1[1],pole2[1]] , 'rx' , label = "Poles of $Y(z)$")
plt.plot(zero[0] , zero[1] , 'ro' , label = "Zeroes of $Y(z)$")
plt.title("Pole-Zero Plot with ROC of $Y(z)$")
plt.xlabel('Real axis')
plt.ylabel('Imaginary axis')
plt.grid()
plt.legend()
plt.show()