# -*- coding: utf-8 -*-
"""Gate_Assignment_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCPcWDLbQuvNdI1JJFPCPjfamI4KDg3t
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy.signal import unit_impulse

n = np.arange(-2,7)
y_n = (1/2)*unit_impulse(9)+unit_impulse(9,2)+2*unit_impulse(9,4)+unit_impulse(9,6)+(1/2)*unit_impulse(9,8)

#Plotting
plt.stem(n,y_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()